# Generated by Django 4.2.3 on 2023-07-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_lowfound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
