# Generated by Django 4.2.3 on 2023-07-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_lowfound', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
